name: "Estruturas de Diretorios e Arquivos"

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

  env:
    NODE_VERSION: '18'

    jobs:
      demonstrando-estrutura:
        name: "Demonstrar Estrutura Básica"
        runs-on: ubuntu-lastest

        steps:
          - name: Checkout do Codigo
            user: actions/checkout@v4

          - name: Mostrar estrutura .github/workflows
            run: |
             echo " == ESTRUTURA DE DIRETORIOS E ARQUIVOS .github/workflows == "
             ls -la .github/workflows
             echo ""
             echo " Total de workflows: $(ls -l .github/workflows | wc -l) "

          - name: Elementos Obrigatorios do workflow
            run: |
              echo " == ELEMENTOS OBRIGATORIOS DO WORKFLOW == "
              echo " 1. name: Nome do workflow"
              echo " 2. on: Evento que aciona o workflow"
              echo " 3. jobs: Conjunto de tarefas a serem executadas"
              echo " 4. runs-on: Ambiente onde o job será executado"
              echo " 5. steps: Passos a serem executados dentro do job" 
              echo ""
              echo " Total de elementos obrigatorios: 5 "

          - name: Variaveis e Contexto
            run: |
              echo " == VARIAVEIS E CONTEXTO == "
              echo " Variaveis env: { env.NODE_VERSION } "
              echo " 1, ENV: Definição de variáveis de ambiente"
              echo " 2. contextos: Acesso a informarções do workflow, job, runner, etc"
              echo ""
              echo " Total de variaveis e contextos: 2 "
